import type { jsPDF } from "jspdf"

export async function loadLogoDataUrl() {
  const response = await fetch("/black.png")
  const blob = await response.blob()

  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result))
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

export async function captureChartDataUrl(elementId: string) {
  const container = document.getElementById(elementId)
  const svg = container?.querySelector("svg")

  if (!svg) {
    throw new Error(`Chart ${elementId} is not available`)
  }

  const bounds = svg.getBoundingClientRect()
  const width = Math.max(640, Math.ceil(bounds.width || 640))
  const height = Math.max(300, Math.ceil(bounds.height || 300))
  const exportSvg = svg.cloneNode(true) as SVGSVGElement
  exportSvg.setAttribute("xmlns", "http://www.w3.org/2000/svg")
  exportSvg.setAttribute("width", String(width))
  exportSvg.setAttribute("height", String(height))
  exportSvg.setAttribute("viewBox", `0 0 ${width} ${height}`)
  const serializedSvg = new XMLSerializer().serializeToString(exportSvg)
  const blob = new Blob([serializedSvg], {
    type: "image/svg+xml;charset=utf-8",
  })
  const objectUrl = URL.createObjectURL(blob)

  try {
    const image = await new Promise<HTMLImageElement>((resolve, reject) => {
      const nextImage = new Image()
      nextImage.onload = () => resolve(nextImage)
      nextImage.onerror = () => reject(new Error(`Failed to render ${elementId}`))
      nextImage.src = objectUrl
    })
    const canvas = document.createElement("canvas")
    canvas.width = width * 2
    canvas.height = height * 2
    const context = canvas.getContext("2d")

    if (!context) {
      throw new Error("Canvas is unavailable")
    }

    context.scale(2, 2)
    context.fillStyle = "#ffffff"
    context.fillRect(0, 0, width, height)
    context.drawImage(image, 0, 0, width, height)
    return canvas.toDataURL("image/png")
  } finally {
    URL.revokeObjectURL(objectUrl)
  }
}

export function addPdfFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text("Generated by StockDashboard", 14, 287)
    doc.text(`Page ${page} of ${pageCount}`, 196, 287, { align: "right" })
  }
}
