import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"
import {
  Bar,
  BarChart,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts"
import { Download } from "lucide-react"
import type { AuthUser } from "../auth/authTypes"
import type { Collaborator } from "../collaborators/collaboratorsTypes"
import type { Part } from "../inventory/inventoryTypes"
import type { Purchase } from "../purchases/purchasesTypes"
import type { MissingItemRequest, PartRequest } from "../requests/requestsTypes"
import type { AnalyticsSummary } from "./analyticsTypes"
import { StatCard } from "../dashboard/DashboardCards"
import { AnalyticsTable, ChartCard } from "./AnalyticsCharts"
import { formatMoney as formatCurrency } from "../../shared/utils/formatMoney"
import { getTodayDate } from "../../shared/utils/formatDate"
import {
  addPdfFooter,
  captureChartDataUrl,
  loadLogoDataUrl,
} from "../../shared/utils/downloadReports"

const categoryColorMap: Record<string, string> = {
  Microprocessors: "#facc15",
  Microcontrollers: "#2563eb",
  PCBs: "#16a34a",
  Sensors: "#dc2626",
  Actuators: "#9333ea",
  "Development Boards": "#0891b2",
  "Communication Modules": "#ea580c",
  Connectors: "#4f46e5",
  Cables: "#65a30d",
  "Power Modules": "#be123c",
  "Test Equipment": "#0f766e",
  Tools: "#7c2d12",
  Other: "#64748b",
}

function PartStatusBadge({ status }: { status: string }) {
  const classes =
    status === "Available"
      ? "bg-green-100 text-green-800"
      : status === "Low Stock"
        ? "bg-orange-100 text-orange-800"
        : status === "Not Available"
          ? "bg-red-100 text-red-800"
          : status === "Reserved"
            ? "bg-yellow-100 text-yellow-800"
            : status === "Borrowed"
              ? "bg-blue-100 text-blue-800"
              : status === "Damaged"
                ? "bg-gray-200 text-gray-800"
                : "bg-gray-100 text-gray-800"

  return (
    <span
      className={`inline-flex rounded-full px-3 py-1 text-sm font-semibold ${classes}`}
    >
      {status}
    </span>
  )
}
export function AnalyticsPage({
  analyticsSummary,
  isLoadingAnalytics,
  analyticsError,
  currentUser,
  parts,
  partRequests,
  missingItemRequests,
  purchases,
  collaborators,
  users,
  lowStockThreshold,
}: {
  analyticsSummary: AnalyticsSummary | null
  isLoadingAnalytics: boolean
  analyticsError: string | null
  currentUser: AuthUser
  parts: Part[]
  partRequests: PartRequest[]
  missingItemRequests: MissingItemRequest[]
  purchases: Purchase[]
  collaborators: Collaborator[]
  users: AuthUser[]
  lowStockThreshold: number
}) {
  const inventoryByCategory =
    analyticsSummary?.inventoryByCategory.map((category) => ({
      name: category.category,
      value: category.count,
    })) || []
  const divisionAnalytics = analyticsSummary?.reservationsByDivision || []
  const groupAnalytics = analyticsSummary?.borrowedPartsByGroup || []
  const currency = analyticsSummary?.currency || "EUR"
  const spendingByCategory = analyticsSummary?.spendingByCategory || []
  const spendingBySupplier = analyticsSummary?.spendingBySupplier || []
  const spendingByDivision = analyticsSummary?.spendingByDivision || []

  async function downloadAnalyticsPdf() {
    if (!analyticsSummary) {
      return
    }

    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" })
    const generatedAt = new Date()
    let y = 18

    try {
      const logo = await loadLogoDataUrl()
      doc.addImage(logo, "PNG", 14, 9, 38, 12)
    } catch {
      // The report remains usable if the optional logo cannot be loaded.
    }

    doc.setFontSize(18)
    doc.setFont("helvetica", "bold")
    doc.text("StockDashboard Inventory Report", 58, 17)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    doc.text(`Generated: ${generatedAt.toLocaleString()}`, 58, 23)
    doc.text(
      `Generated by: ${currentUser.name} (${currentUser.role})`,
      58,
      28
    )
    y = 38

    const section = (title: string) => {
      if (y > 180) {
        doc.addPage()
        y = 16
      }
      doc.setFont("helvetica", "bold")
      doc.setFontSize(13)
      doc.text(title, 14, y)
      y += 5
    }
    const afterTable = () => {
      const tableDoc = doc as jsPDF & {
        lastAutoTable?: { finalY: number }
      }
      y = (tableDoc.lastAutoTable?.finalY || y) + 9
    }
    const table = (
      head: string[][],
      body: Array<Array<string | number>>,
      options: Record<string, unknown> = {}
    ) => {
      autoTable(doc, {
        startY: y,
        head,
        body: body.length ? body : [["No data available"]],
        theme: "grid",
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [31, 41, 55] },
        ...options,
      })
      afterTable()
    }

    const availableQuantity = parts.reduce(
      (sum, part) => sum + (part.availableQuantity || 0),
      0
    )
    const reservedQuantity = parts.reduce(
      (sum, part) => sum + (part.reservedQuantity || 0),
      0
    )
    const borrowedQuantity = parts.reduce(
      (sum, part) => sum + (part.borrowedQuantity || 0),
      0
    )
    const damagedQuantity = parts.reduce(
      (sum, part) => sum + (part.damagedQuantity || 0),
      0
    )
    const pendingRequests =
      partRequests.filter((request) => request.status === "Pending").length +
      missingItemRequests.filter((request) => request.status === "Pending").length
    const pendingPurchases = purchases.filter((purchase) =>
      ["Pending", "Approved", "Ordered", "In Transit"].includes(purchase.status)
    ).length

    section("Executive Summary")
    table(
      [
        [
          "Total Parts",
          "Available",
          "Reserved",
          "Borrowed",
          "Damaged",
          "Low Stock",
          "Collaborators",
          "Pending Requests",
          "Pending Purchases",
        ],
      ],
      [
        [
          analyticsSummary.totalParts,
          availableQuantity,
          reservedQuantity,
          borrowedQuantity,
          damagedQuantity,
          analyticsSummary.lowStockParts,
          analyticsSummary.totalCollaborators,
          pendingRequests,
          pendingPurchases,
        ],
      ]
    )

    section("Financial Summary")
    table(
      [
        [
          "Total Spent",
          "Pending Purchase Value",
          "Spent This Month",
          "Spent This Year",
          "Average Unit Price",
        ],
      ],
      [
        [
          formatCurrency(analyticsSummary.totalSpent, currency),
          formatCurrency(analyticsSummary.pendingPurchaseValue, currency),
          formatCurrency(analyticsSummary.spentThisMonth, currency),
          formatCurrency(analyticsSummary.spentThisYear, currency),
          formatCurrency(analyticsSummary.averageUnitPrice, currency),
        ],
      ]
    )
    section("Spending by Category")
    table(
      [["Category", "Spent"]],
      analyticsSummary.spendingByCategory.map((item) => [
        item.category,
        formatCurrency(item.total, currency),
      ])
    )
    section("Spending by Supplier")
    table(
      [["Supplier", "Spent"]],
      analyticsSummary.spendingBySupplier.map((item) => [
        item.supplier,
        formatCurrency(item.total, currency),
      ])
    )
    section("Top 5 Most Expensive Purchases")
    table(
      [["Purchase", "Category", "Supplier", "Quantity", "Total"]],
      analyticsSummary.topExpensivePurchases.map((purchase) => [
        `#${purchase.id} ${purchase.itemName}`,
        purchase.category,
        purchase.supplier,
        purchase.quantity,
        formatCurrency(purchase.total, currency),
      ])
    )

    doc.addPage()
    doc.setFont("helvetica", "bold")
    doc.setFontSize(16)
    doc.text("Analytics Charts", 14, 16)
    const chartDefinitions = [
      {
        id: "analytics-inventory-category-chart",
        title: "Inventory by Category",
        x: 10,
        fallbackHead: [["Category", "Parts"]],
        fallbackBody: analyticsSummary.inventoryByCategory.map((item) => [
          item.category,
          item.count,
        ]),
      },
      {
        id: "analytics-reservations-division-chart",
        title: "Reservations by Division",
        x: 106,
        fallbackHead: [["Division", "Reserved", "Borrowed Qty"]],
        fallbackBody: analyticsSummary.reservationsByDivision.map((item) => [
          item.division,
          item.activeReservations,
          item.borrowedParts,
        ]),
      },
      {
        id: "analytics-borrowed-group-chart",
        title: "Borrowed Parts by Group",
        x: 202,
        fallbackHead: [["Group", "Borrowed Qty"]],
        fallbackBody: analyticsSummary.borrowedPartsByGroup.map((item) => [
          item.group,
          item.borrowedParts,
        ]),
      },
    ]
    const failedCharts: typeof chartDefinitions = []

    for (const chart of chartDefinitions) {
      doc.setFontSize(10)
      doc.text(chart.title, chart.x, 25)
      try {
        const image = await captureChartDataUrl(chart.id)
        doc.addImage(image, "PNG", chart.x, 29, 85, 58)
      } catch {
        failedCharts.push(chart)
        doc.setDrawColor(209, 213, 219)
        doc.rect(chart.x, 29, 85, 58)
        doc.setFont("helvetica", "normal")
        doc.setFontSize(9)
        doc.text("Chart unavailable. See table fallback.", chart.x + 5, 58)
      }
    }

    if (failedCharts.length > 0) {
      y = 100
      for (const chart of failedCharts) {
        section(`${chart.title} - Table Fallback`)
        table(chart.fallbackHead, chart.fallbackBody)
      }
    } else {
      y = 100
    }

    section("Inventory Overview")
    table(
      [
        [
          "Name",
          "Category",
          "Reference",
          "Total",
          "Available",
          "Reserved",
          "Borrowed",
          "Damaged",
          "Location",
          "Status",
        ],
      ],
      parts.map((part) => [
        part.name,
        part.category,
        part.reference,
        part.totalQuantity ?? part.quantity ?? 0,
        part.availableQuantity ?? part.quantity ?? 0,
        part.reservedQuantity ?? 0,
        part.borrowedQuantity ?? 0,
        part.damagedQuantity ?? 0,
        part.location,
        part.status,
      ]),
      { tableWidth: "auto" }
    )

    section("Requests Summary")
    table(
      [["Pending", "Borrowed", "Reserved", "Returned", "Damaged"]],
      [
        [
          pendingRequests,
          partRequests.filter((request) => request.status === "Borrowed").length,
          partRequests.filter((request) => request.status === "Reserved").length,
          partRequests.filter((request) => request.status === "Returned").length,
          partRequests.filter((request) => request.status === "Damaged").length,
        ],
      ]
    )

    section("Purchase Summary")
    table(
      [["Pending", "Ordered", "Received", "Cancelled"]],
      [
        [
          purchases.filter((purchase) => purchase.status === "Pending").length,
          purchases.filter((purchase) => purchase.status === "Ordered").length,
          purchases.filter((purchase) => purchase.status === "Received").length,
          purchases.filter((purchase) => purchase.status === "Cancelled").length,
        ],
      ]
    )

    section("Collaborator Summary")
    table(
      [["Collaborators", "Managers", "Admins", "Average Rating"]],
      [
        [
          collaborators.length,
          users.filter((user) => user.role === "Inventory Manager").length,
          users.filter((user) => user.role === "Admin").length,
          collaborators.length
            ? (
              collaborators.reduce(
                (sum, collaborator) => sum + (collaborator.rating || 0),
                0
              ) / collaborators.length
            ).toFixed(1)
            : "No data available",
        ],
      ]
    )
    table(
      [["Top Active Collaborator", "Reservations", "Borrowed"]],
      analyticsSummary.mostActiveCollaborators.slice(0, 10).map((item) => [
        item.collaboratorName,
        item.reservationCount,
        item.borrowedCount,
      ])
    )

    section("Low Stock")
    table(
      [["Part", "Reference", "Available", "Threshold", "Status"]],
      parts
        .filter((part) => (part.availableQuantity ?? part.quantity ?? 0) <= lowStockThreshold)
        .map((part) => [
          part.name,
          part.reference,
          part.availableQuantity ?? part.quantity ?? 0,
          lowStockThreshold,
          part.status,
        ])
    )

    addPdfFooter(doc)
    doc.save(`stockdashboard-report-${getTodayDate()}.pdf`)
  }

  if (isLoadingAnalytics) {
    return (
      <>
        <h2 className="text-3xl font-bold mb-8">Analytics</h2>
        <div className="bg-white rounded-lg shadow p-6">Loading analytics...</div>
      </>
    )
  }

  if (analyticsError || !analyticsSummary) {
    return (
      <>
        <h2 className="text-3xl font-bold mb-8">Analytics</h2>
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-6">
          Failed to load analytics
        </div>
      </>
    )
  }

  return (
    <>
      <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <h2 className="text-3xl font-bold">Analytics</h2>
        <button
          onClick={downloadAnalyticsPdf}
          className="inline-flex items-center justify-center gap-2 rounded bg-yellow-400 px-4 py-2 font-semibold text-black transition hover:bg-yellow-300"
        >
          <Download className="h-4 w-4" />
          Download PDF Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">
        <StatCard label="Total Parts" value={String(analyticsSummary.totalParts)} />
        <StatCard
          label="Available Parts"
          value={String(analyticsSummary.availableParts)}
          color="text-green-600"
        />
        <StatCard
          label="Borrowed Parts"
          value={String(analyticsSummary.borrowedParts)}
          color="text-blue-600"
        />
        <StatCard
          label="Reserved Parts"
          value={String(analyticsSummary.reservedParts)}
          color="text-yellow-600"
        />
        <StatCard
          label="Damaged Parts"
          value={String(
            analyticsSummary.damagedParts ??
            parts.reduce((total, part) => total + part.damagedQuantity, 0)
          )}
          color="text-red-700"
        />
        <StatCard
          label="Total Collaborators"
          value={String(analyticsSummary.totalCollaborators)}
        />
        <StatCard
          label="Active Borrowers"
          value={String(analyticsSummary.activeBorrowers)}
          color="text-blue-600"
        />
        <StatCard
          label="Low Stock Parts"
          value={String(analyticsSummary.lowStockParts)}
          color="text-red-600"
        />
      </div>

      <h3 className="mb-4 text-xl font-bold">Financial Analytics</h3>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-4 mb-8">
        <StatCard
          label="Total Spent"
          value={formatCurrency(analyticsSummary.totalSpent, currency)}
          color="text-green-700"
        />
        <StatCard
          label="Pending Purchase Value"
          value={formatCurrency(
            analyticsSummary.pendingPurchaseValue,
            currency
          )}
          color="text-yellow-700"
        />
        <StatCard
          label="Spent This Month"
          value={formatCurrency(analyticsSummary.spentThisMonth, currency)}
          color="text-blue-700"
        />
        <StatCard
          label="Spent This Year"
          value={formatCurrency(analyticsSummary.spentThisYear, currency)}
          color="text-purple-700"
        />
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
        <ChartCard title="Spending by Category">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={spendingByCategory}>
              <XAxis dataKey="category" tick={{ fontSize: 11 }} />
              <YAxis />
              <Tooltip formatter={(value) => formatCurrency(Number(value), currency)} />
              <Bar dataKey="total" name="Spent" fill="#2563eb" />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
        <ChartCard title="Spending by Supplier">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={spendingBySupplier}>
              <XAxis dataKey="supplier" tick={{ fontSize: 11 }} />
              <YAxis />
              <Tooltip formatter={(value) => formatCurrency(Number(value), currency)} />
              <Bar dataKey="total" name="Spent" fill="#16a34a" />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
        <ChartCard title="Spending by Division">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={spendingByDivision}>
              <XAxis dataKey="division" tick={{ fontSize: 11 }} />
              <YAxis />
              <Tooltip formatter={(value) => formatCurrency(Number(value), currency)} />
              <Bar dataKey="total" name="Spent" fill="#ca8a04" />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
        <ChartCard
          title="Inventory by Category"
          chartId="analytics-inventory-category-chart"
        >
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie
                data={inventoryByCategory}
                dataKey="value"
                nameKey="name"
                outerRadius={90}
                label
              >
                {inventoryByCategory.map((entry) => (
                  <Cell
                    key={entry.name}
                    fill={
                      categoryColorMap[entry.name] ||
                      categoryColorMap.Other ||
                      "#64748b"
                    }
                  />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard
          title="Reservations by Division"
          chartId="analytics-reservations-division-chart"
        >
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={divisionAnalytics}>
              <XAxis dataKey="division" tick={{ fontSize: 12 }} />
              <YAxis allowDecimals={false} />
              <Tooltip />
              <Bar
                dataKey="activeReservations"
                name="Reserved requests"
                fill="#facc15"
              />
              <Bar
                dataKey="borrowedParts"
                name="Borrowed quantity"
                fill="#2563eb"
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard
          title="Borrowed Parts by Group"
          chartId="analytics-borrowed-group-chart"
        >
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={groupAnalytics}>
              <XAxis dataKey="group" tick={{ fontSize: 12 }} />
              <YAxis allowDecimals={false} />
              <Tooltip />
              <Bar
                dataKey="borrowedParts"
                name="Borrowed quantity"
                fill="#2563eb"
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <AnalyticsTable title="Top 5 Most Expensive Purchases">
          <table className="w-full min-w-[640px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Purchase</th>
                <th className="text-left py-3 px-2">Category</th>
                <th className="text-left py-3 px-2">Supplier</th>
                <th className="text-left py-3 px-2">Quantity</th>
                <th className="text-left py-3 px-2">Total</th>
              </tr>
            </thead>
            <tbody>
              {analyticsSummary.topExpensivePurchases.map((purchase) => (
                <tr key={purchase.id} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-2 font-medium">
                    #{purchase.id} {purchase.itemName}
                  </td>
                  <td className="py-3 px-2">{purchase.category}</td>
                  <td className="py-3 px-2">{purchase.supplier}</td>
                  <td className="py-3 px-2">{purchase.quantity}</td>
                  <td className="py-3 px-2 font-semibold">
                    {formatCurrency(purchase.total, currency)}
                  </td>
                </tr>
              ))}
              {analyticsSummary.topExpensivePurchases.length === 0 && (
                <tr>
                  <td colSpan={5} className="py-6 text-center text-gray-500">
                    No received purchase spending yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </AnalyticsTable>

        <AnalyticsTable title="Low Stock Analysis">
          <table className="w-full min-w-[560px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Part Name</th>
                <th className="text-left py-3 px-2">Category</th>
                <th className="text-left py-3 px-2">Available Quantity</th>
                <th className="text-left py-3 px-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {analyticsSummary.lowStockItems.map((part) => (
                <tr key={part.id} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-2 font-medium">{part.name}</td>
                  <td className="py-3 px-2">{part.category}</td>
                  <td className="py-3 px-2">{part.availableQuantity}</td>
                  <td className="py-3 px-2">
                    <PartStatusBadge status={part.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </AnalyticsTable>

        <AnalyticsTable title="Most Borrowed Parts">
          <table className="w-full min-w-[520px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Rank</th>
                <th className="text-left py-3 px-2">Part Name</th>
                <th className="text-left py-3 px-2">Borrow Count</th>
              </tr>
            </thead>
            <tbody>
              {analyticsSummary.mostBorrowedParts.map((part, index) => (
                <tr key={part.partName} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-2">{index + 1}</td>
                  <td className="py-3 px-2 font-medium">{part.partName}</td>
                  <td className="py-3 px-2">{part.borrowCount}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </AnalyticsTable>

        <AnalyticsTable title="Most Active Collaborators">
          <table className="w-full min-w-[640px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Rank</th>
                <th className="text-left py-3 px-2">Collaborator</th>
                <th className="text-left py-3 px-2">Total Reservations</th>
                <th className="text-left py-3 px-2">Borrowed Items</th>
              </tr>
            </thead>
            <tbody>
              {analyticsSummary.mostActiveCollaborators.map((collaborator, index) => (
                <tr
                  key={collaborator.collaboratorName}
                  className="border-b hover:bg-gray-50"
                >
                  <td className="py-3 px-2">{index + 1}</td>
                  <td className="py-3 px-2 font-medium">
                    {collaborator.collaboratorName}
                  </td>
                  <td className="py-3 px-2">
                    {collaborator.reservationCount}
                  </td>
                  <td className="py-3 px-2">{collaborator.borrowedCount}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </AnalyticsTable>

        <AnalyticsTable title="Division Analytics">
          <table className="w-full min-w-[620px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Division</th>
                <th className="text-left py-3 px-2">Collaborators</th>
                <th className="text-left py-3 px-2">Active Reservations</th>
                <th className="text-left py-3 px-2">Borrowed Parts</th>
                <th className="text-left py-3 px-2">Returned</th>
                <th className="text-left py-3 px-2">Damaged</th>
              </tr>
            </thead>
            <tbody>
              {divisionAnalytics.map((division) => (
                <tr key={division.division} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-2 font-medium">{division.division}</td>
                  <td className="py-3 px-2">{division.collaborators}</td>
                  <td className="py-3 px-2">{division.activeReservations}</td>
                  <td className="py-3 px-2">{division.borrowedParts}</td>
                  <td className="py-3 px-2">{division.returnedParts || 0}</td>
                  <td className="py-3 px-2">{division.damagedParts || 0}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </AnalyticsTable>

        <AnalyticsTable title="Group Analytics">
          <table className="w-full min-w-[620px]">
            <thead>
              <tr className="border-b bg-gray-100">
                <th className="text-left py-3 px-2">Group</th>
                <th className="text-left py-3 px-2">Collaborators</th>
                <th className="text-left py-3 px-2">Active Reservations</th>
                <th className="text-left py-3 px-2">Borrowed Parts</th>
                <th className="text-left py-3 px-2">Returned</th>
                <th className="text-left py-3 px-2">Damaged</th>
              </tr>
            </thead>
            <tbody>
              {groupAnalytics.map((group) => (
                <tr key={group.group} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-2 font-medium">{group.group}</td>
                  <td className="py-3 px-2">{group.collaborators}</td>
                  <td className="py-3 px-2">{group.activeReservations}</td>
                  <td className="py-3 px-2">{group.borrowedParts}</td>
                  <td className="py-3 px-2">{group.returnedParts || 0}</td>
                  <td className="py-3 px-2">{group.damagedParts || 0}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </AnalyticsTable>
      </div>
    </>
  )
}

